### ISSUE TITLE
kodi访问jellyfin服务失败，错误码[WinError 10060] 

### ISSUE THREAD

**Issue by ThunderboltSky** [xbmc/kodi-tv#812] opened 2024-03-05 05:06 UTC
>
![屏幕截图 2024-03-05 130220](https://github.com/xbmc/kodi-tv/assets/160369749/5f5edd15-a1d5-47c3-b7bf-268a7fb038e7)
连接jellyfin一段时间后就出现断开连接的情况，如果重新生成插件ID，或者重置kodi的数据库，可以短暂连接到，过一会就又会断开连接。软件提示【一个项目或多个项目播放失败】，上图是错误日志

**Comment by KarellenX** [comment] 2024-03-05 05:11
Please complete the full template and use English.

If I the problem is what I think it is, then the Jellyfin addon needs an update. Contact the Jellyfin developer.

**Comment by KarellenX** [comment] 2024-03-05 06:11
I just noticed you posted in the wrong repository, so I'll go ahead and close this.

If you have any questions, please ask them in the forum in English... https://forum.kodi.tv/index.php

**Closed by KarellenX** 2024-03-05 06:11 UTC
